### ISSUE TITLE
fix broken link in readme.md for membership.md

### ISSUE THREAD

**Issue by rahulkumaran** [MEC-Enigma/Hacktoberfest18#2]
Currently, the link for membership.md is broken in readme.md
Anyone who thinks can solve this easily, please comment here.
The issue will be assigned to you! 

PS : <b>ONLY</b> beginners can take this issue up

**Comment by deadbeatfour** [comment]
I'm getting starting with open source, I'd like to fix this issue

**Comment by rahulkumaran** [comment]
@deadbeatfour Would've loved to hand this issue over to you but it looks like you've already made some contributions here on Github.
You could perhaps take up other issues that we put up throughout this month. Let this stay for someone who's actually making their first contibution or something.

**Comment by deadbeatfour** [comment]
@rahulkumaran Of course. Cheers!

**Comment by federhico** [comment]
Can I ?

**Comment by mohancm** [comment]
@rahulkumaran only beginners to this repo or github?

**Comment by IceCereal** [comment]
It'd be better for the members who are new to GitHub and are learning about Open Source to work on this issue.
